name: UniVI_working_environment_v2
channels:
  - plotly
  - intel
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38h06a4308_1
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _r-mutex=1.0.1=anacondar_1
  - alabaster=0.7.13=pyhd8ed1ab_0
  - alsa-lib=1.2.3.2=h166bdaf_0
  - anaconda=custom=py38_1
  - anaconda-client=1.11.1=pyhd8ed1ab_0
  - anaconda-navigator=2.3.2=py38h06a4308_0
  - anaconda-project=0.11.1=pyhd8ed1ab_0
  - anndata=0.8.0=pyhd8ed1ab_1
  - anndata2ri=1.1=pyhdfd78af_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h0a891b7_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - arviz=0.11.2=pyhd8ed1ab_0
  - asn1crypto=1.5.1=py38h06a4308_0
  - astroid=2.15.0=py38h578d9bd_0
  - astropy=5.2.1=py38h7e4f40d_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - autopep8=1.5.5=pyh44b312d_0
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports.zoneinfo=0.2.1=py38h0a891b7_7
  - beautifulsoup4=4.11.2=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - binutils_impl_linux-64=2.35.1=h193b22a_2
  - binutils_linux-64=2.35.1=h454624a_30
  - bitarray=2.7.3=py38h1de0b5d_0
  - bkcharts=0.2=py38h06a4308_1
  - black=23.1.0=py38h578d9bd_0
  - blas=2.106=openblas
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.3=hafa529b_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boto=2.49.0=py_0
  - bottleneck=1.3.6=py38h7e4f40d_0
  - brotli=1.0.9=hf484d3e_2
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hb9a14ef_9
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=py_0
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.14.5=py38h3040615_0
  - cftime=1.6.2=py38h26c90d9_1
  - chardet=5.1.0=py38h578d9bd_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - clyent=1.2.2=py_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - conda=23.1.0=py38h578d9bd_0
  - conda-build=3.23.3=py38h578d9bd_1
  - conda-content-trust=0.1.3=pyhd8ed1ab_0
  - conda-env=2.6.0=1
  - conda-pack=0.7.0=pyh6c4a22f_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.7.0=pyhd8ed1ab_1
  - conda-repo-cli=1.0.27=py38h06a4308_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.1.1=py38h578d9bd_1006
  - contextlib2=21.6.0=pyhd8ed1ab_0
  - contourpy=1.0.7=py38hfbd4bf9_0
  - cookiecutter=2.1.1=pyh6c4a22f_0
  - cryptography=38.0.4=py38h2b5fc30_0
  - curl=7.77.0=hea6ffbf_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.33=py38h8dc9893_0
  - cytoolz=0.12.0=py38h0a891b7_1
  - dask=2023.3.0=pyhd8ed1ab_0
  - dask-core=2023.3.0=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.6.6=py38h8dc9893_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - dill=0.3.6=pyhd8ed1ab_1
  - distributed=2023.3.0=pyhd8ed1ab_0
  - docutils=0.19=py38h578d9bd_1
  - dpcpp-cpp-rt=2022.1.0=intel_3768
  - dpcpp_cpp_rt=2023.0.0=intel_25370
  - dunamai=1.16.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - enum34=1.1.10=py38h32f6830_2
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fastcache=1.1.0=py38h0a891b7_5
  - fbpca=1.0=py_0
  - filelock=3.9.0=pyhd8ed1ab_0
  - flake8=3.8.4=py_0
  - flask=2.2.3=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.0=py38h1de0b5d_0
  - freetype=2.12.1=hb267b13_2
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2023.3.0=pyhd8ed1ab_1
  - future=0.18.3=pyhd8ed1ab_0
  - gcc_impl_linux-64=9.3.0=h6df7d76_17
  - gcc_linux-64=9.3.0=h1ee779e_30
  - geosketch=1.2=py_0
  - get_terminal_size=1.0.0=haa9412d_0
  - get_version=3.5.1=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - gevent=22.10.2=py38h0fd6f59_0
  - gfortran_impl_linux-64=9.3.0=hc4a2995_19
  - gfortran_linux-64=9.3.0=hf47db2c_30
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - glob2=0.7=py_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py38h793c122_1
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=2.0.2=py38h8dc9893_0
  - gsl=2.6=he838d99_2
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - gxx_impl_linux-64=9.3.0=hbdd7822_17
  - gxx_linux-64=9.3.0=h7e70986_30
  - h5py=3.3.0=nompi_py38h9915d05_100
  - harfbuzz=2.8.1=h83ec7ef_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - html5lib=1.1=pyh9f0ad1d_0
  - icc_rt=2022.1.0=intel_3768
  - icu=68.2=h9c3ff4c_0
  - idna=3.4=py38h06a4308_0
  - imagecodecs-lite=2019.12.3=py38h26c90d9_6
  - imageio=2.26.0=pyh24c5eb1_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intel-cmplr-lib-rt=2022.1.0=intel_3768
  - intel-cmplr-lic-rt=2022.1.0=intel_3768
  - intel-opencl-rt=2022.1.0=intel_3768
  - intel-openmp=2022.1.0=intel_3768
  - intelpython=2023.0.0=1
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.21.2=pyh210e3f2_0
  - ipython=8.11.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - isort=5.12.0=pyhd8ed1ab_1
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.2.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jdcal=1.4.1=py_0
  - jedi=0.17.2=py38h578d9bd_2
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h7f8727e_1
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h578d9bd_8
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py38h578d9bd_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.4.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=3.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.20.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyring=23.13.1=py38h578d9bd_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h43d8883_1
  - krb5=1.19.3=h3790be6_0
  - lazy-object-proxy=1.9.0=py38h1de0b5d_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.5.2=hccf745f_1
  - libblas=3.9.0=6_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=6_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.77.0=h2574ce0_0
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=he436679_1
  - libffi=3.3=14
  - libgcc-devel_linux-64=9.3.0=hb95220a_17
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=9.3.0=ha5ec8a7_17
  - libgfortran5=9.3.0=ha5ec8a7_17
  - libglib=2.68.3=h3e27bee_0
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=6_openblas
  - liblapacke=3.9.0=6_openblas
  - liblief=0.12.3=h27087fc_0
  - libllvm11=11.1.0=he0ac6c6_5
  - libllvm9=9.0.1=default_hc23dcda_7
  - libnetcdf=4.8.0=nompi_hcd642e3_103
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=13.3=hd57d9b9_3
  - libprotobuf=3.21.12=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-devel_linux-64=9.3.0=hf0c5c8d_17
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h82bc61c_5
  - libtool=2.4.7=h27087fc_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h7a2d63c_3
  - libxslt=1.1.33=h15afd5d_2
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.39.1=py38h38d86a4_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=4.6.3=py38hf1fe3a4_0
  - lz4=4.3.2=py38hd012fdc_0
  - lz4-c=1.9.3=h688b341_1
  - lzo=2.10=h309b0be_6
  - make=4.3=hd18ef5c_1
  - markupsafe=2.1.2=py38h1de0b5d_0
  - matplotlib=3.7.1=py38h578d9bd_0
  - matplotlib-base=3.7.1=py38hd6c3c57_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mistune=2.0.5=pyhd8ed1ab_0
  - mkl=2022.2.1=intel_16993
  - mkl-service=2.4.0=py38h7634626_12
  - mkl_fft=1.3.1=py38h1909d4f_16
  - mkl_random=1.2.2=py38h94ca54a_16
  - mock=5.0.1=pyhd8ed1ab_0
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py38hfbd4bf9_0
  - multipledispatch=0.6.0=py_0
  - munkres=1.1.4=py_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - natsort=8.3.1=pyhd8ed1ab_0
  - navigator-updater=0.3.0=py38h06a4308_0
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.2=hf61fa16_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.5.7=nompi_py38h5e9db54_100
  - networkx=3.0=pyhd8ed1ab_0
  - nltk=3.8.1=pyhd8ed1ab_0
  - nose=1.3.7=py_1006
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.88=he45b914_0
  - numba=0.56.4=py38h9a4aae9_0
  - numexpr=2.7.3=py38h1d04dd3_4
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - olefile=0.46=pyhd3eb1b0_1
  - openjpeg=2.5.0=h7d73246_1
  - openpyxl=3.1.1=py38h1de0b5d_0
  - openssl=1.1.1t=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py38hdc8b05c_0
  - pandoc=2.19.2=h32600fe_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.48.6=hb8ff022_0
  - parso=0.7.0=pyh9f0ad1d_0
  - partd=1.3.0=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - path=16.6.0=py38h578d9bd_0
  - path.py=12.5.0=0
  - pathlib=1.0.1=py38h578d9bd_7
  - pathlib2=2.3.7.post1=py38h578d9bd_2
  - pathspec=0.11.0=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pep8=1.7.1=py_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py38h9eb91d8_3
  - pip=22.2.2=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.1.0=pyhd8ed1ab_0
  - plotly=5.13.0=py_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py38h0a891b7_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - py-lief=0.12.3=py38hfa26641_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycosat=0.6.4=py38h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pycurl=7.43.0.6=py38h996a351_1
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyerfa=2.0.0.1=py38h26c90d9_3
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyhamcrest=2.0.4=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pylint=2.17.0=pyhd8ed1ab_0
  - pyls-black=0.4.6=pyh9f0ad1d_0
  - pyls-spyder=0.3.2=pyhd8ed1ab_0
  - pyodbc=4.0.35=py38hfa26641_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.12.3=py38h578d9bd_8
  - pyqt-impl=5.12.3=py38h0ffb2e6_8
  - pyqt5-sip=4.19.18=py38h709712a_8
  - pyqtchart=5.12=py38h7400c14_8
  - pyqtwebengine=5.12.1=py38h7400c14_8
  - pyrsistent=0.19.3=py38h1de0b5d_0
  - pysocks=1.7.1=py38h06a4308_0
  - pystan=2.19.1.1=py38h1abd341_3
  - pytables=3.6.1=py38hc386592_3
  - pytest=7.2.2=pyhd8ed1ab_0
  - python=3.8.10=h49503c6_1_cpython
  - python-annoy=1.17.1=py38hfa26641_0
  - python-dateutil=2.8.2=py38_1
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-jsonrpc-server=0.4.0=pyh9f0ad1d_0
  - python-language-server=0.36.2=pyhd8ed1ab_0
  - python-libarchive-c=4.0=py38h578d9bd_2
  - python-slugify=8.0.1=pyhd8ed1ab_0
  - python-tzdata=2022.7=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytorch=1.13.1=cpu_py38hbac4b8a_1
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py38h578d9bd_3
  - pywavelets=1.4.1=py38h7e4f40d_0
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0=py38h7f8727e_1
  - pyzmq=25.0.0=py38he24dcef_0
  - qdarkstyle=3.0.2=pyhd8ed1ab_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt=5.12.9=hda022c4_4
  - qtawesome=1.2.2=pyhd8ed1ab_0
  - qtconsole=5.4.0=pyhd8ed1ab_0
  - qtconsole-base=5.4.0=pyha770c72_0
  - qtpy=2.3.0=pyhd8ed1ab_0
  - r-base=3.6.3=hbcea092_8
  - r-lattice=0.20_38=r36hcdcec82_1002
  - r-matrix=1.2_17=r36hcdcec82_1
  - readline=8.1=h46c0cb4_0
  - regex=2022.10.31=py38h0a891b7_0
  - requests=2.28.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - ripgrep=13.0.0=h2f28480_2
  - rope=1.7.0=pyhd8ed1ab_0
  - rpy2=3.4.5=py38r36hb5d20a5_0
  - rtree=1.0.1=py38h02d302b_1
  - ruamel.yaml=0.17.21=py38h1de0b5d_3
  - ruamel.yaml.clib=0.2.7=py38h1de0b5d_1
  - ruamel_yaml=0.15.80=py38h0a891b7_1008
  - scanorama=1.7.3=pyhdfd78af_0
  - scikit-image=0.19.3=py38h8f669ce_2
  - scikit-learn=1.1.1=py38h6a678d5_0
  - scipy=1.6.3=py38h7b17777_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - secretstorage=3.3.3=py38h578d9bd_1
  - sed=4.8=he412f7d_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=63.4.1=py38h06a4308_0
  - simplegeneric=0.8.1=py_1
  - singledispatch=3.6.1=pyh44b312d_0
  - sip=6.7.7=py38h8dc9893_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h9b69904_2
  - snappy=1.1.9=h295c915_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcollections=2.1.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=6.1.3=pyhd8ed1ab_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sphinxcontrib-websupport=1.2.4=pyhd8ed1ab_1
  - spyder=5.0.5=py38h578d9bd_2
  - spyder-kernels=2.0.4=py38h578d9bd_0
  - sqlalchemy=2.0.5.post1=py38h1de0b5d_0
  - sqlite=3.36.0=hb9a14ef_3
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py38h26c90d9_2
  - stdlib-list=0.8.0=pyhd8ed1ab_0
  - sympy=1.11.1=py38h578d9bd_2
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.7.0=intel_8712
  - tblib=1.7.0=pyhd8ed1ab_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - text-unidecode=1.3=py_0
  - textdistance=4.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tifffile=2019.7.26.2=py38_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tktable=2.10=hb7b940f_3
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.6=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchvision=0.14.1=cpu_py38hb98b4bf_0
  - tornado=6.2=py38h0a891b7_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - tzlocal=4.2=py38h578d9bd_2
  - ujson=5.7.0=py38h8dc9893_0
  - unicodecsv=0.14.1=py_1
  - unicodedata2=15.0.0=py38h0a891b7_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - unixodbc=2.3.10=h583eb01_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - watchdog=2.3.1=py38h578d9bd_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - wrapt=1.15.0=py38h1de0b5d_0
  - wurlitzer=3.0.3=pyhd8ed1ab_0
  - xarray=2022.11.0=pyhd8ed1ab_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xlsxwriter=3.0.8=pyhd8ed1ab_0
  - xlwt=1.3.0=py_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.32.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zope=1.0=py38_1
  - zope.event=4.6=pyhd8ed1ab_0
  - zope.interface=5.5.2=py38h0a891b7_0
  - zstandard=0.19.0=py38h5945529_1
  - zstd=1.5.2=ha4553b6_2
  - pip:
      - mizani==0.9.3
      - mudata==0.2.2
      - muon==0.1.3
      - numpy==1.21.5
      - plotnine==0.12.4
      - protobuf==4.23.2
      - pynndescent==0.5.10
      - scanpy==1.9.3
      - umap-learn==0.5.3
prefix: /home/groups/precepts/ashforda/anaconda3/envs/UniVI_working_environment_v2
